// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfPvcxDG1N5gWNroAuWpP-dP437AWyNDA',
    appId: '1:212655381778:web:fdd2e80378a17f6d47a7cb',
    messagingSenderId: '212655381778',
    projectId: 'flow-wallet-8cbd3',
    authDomain: 'flow-wallet-8cbd3.firebaseapp.com',
    storageBucket: 'flow-wallet-8cbd3.firebasestorage.app',
    measurementId: 'G-4PEFCZ0V08',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3oiZSz8f810kQ_zFX8n2CvzaD42H1jlI',
    appId: '1:212655381778:android:cd8a65ac49f816b647a7cb',
    messagingSenderId: '212655381778',
    projectId: 'flow-wallet-8cbd3',
    storageBucket: 'flow-wallet-8cbd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9DKsvzA4KqhenMotW0ILCf4z0YahhXuE',
    appId: '1:212655381778:ios:54864a7cef005f1e47a7cb',
    messagingSenderId: '212655381778',
    projectId: 'flow-wallet-8cbd3',
    storageBucket: 'flow-wallet-8cbd3.firebasestorage.app',
    iosBundleId: 'com.example.flowWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9DKsvzA4KqhenMotW0ILCf4z0YahhXuE',
    appId: '1:212655381778:ios:54864a7cef005f1e47a7cb',
    messagingSenderId: '212655381778',
    projectId: 'flow-wallet-8cbd3',
    storageBucket: 'flow-wallet-8cbd3.firebasestorage.app',
    iosBundleId: 'com.example.flowWallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfPvcxDG1N5gWNroAuWpP-dP437AWyNDA',
    appId: '1:212655381778:web:182d09544ceec6cd47a7cb',
    messagingSenderId: '212655381778',
    projectId: 'flow-wallet-8cbd3',
    authDomain: 'flow-wallet-8cbd3.firebaseapp.com',
    storageBucket: 'flow-wallet-8cbd3.firebasestorage.app',
    measurementId: 'G-4WMWC8PC7D',
  );
}
